matrix:
- name: markdown
  aspell:
    lang: en
    d: en_US
    ignore-case: true
  dictionary:
    wordlists:
      - .github/workflows/config/spellcheck.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - attr_list
      - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - ':matches(code, pre)'
      - code
      - pre
  - pyspelling.filters.url:
  sources:
  - '**/*.md'
  default_encoding: utf-8
