name: check

# restricting branches prevents jobs from being run twice since
# a push to a pull request triggers two events.
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - "*"
  push:
    branches:
      - main


jobs:

  build:  # --------------------------------------------------------------------
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - name: set Material for MkDocs version
        run: echo "MKM_VER=$(cat .mkdocs-material.version)" >> $GITHUB_ENV
      - name: install Material for MkDocs and dependencies
        run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@${MKM_VER}
          pip install -r requirements.txt
      - name: build site
        run: mkdocs build --strict


  yamllint: # ----------------------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: list changed YAML files
        id: changedfiles
        uses: tj-actions/changed-files@v37
        with:
          files: '**.yml'
      - name: lint YAML files
        uses: ibiqlik/action-yamllint@v3
        if: steps.changedfiles.outputs.any_changed == 'true'
        with:
          file_or_dir: ${{ steps.changedfiles.outputs.all_changed_files }}
          config_file: .github/workflows/config/.yamllint


  mdlint: # ----------------------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: list changed Markdown files
        id: changedfiles
        uses: tj-actions/changed-files@v37
        with:
          files: '**.md'
      - name: lint Markdown files
        ses: nosborn/github-action-markdown-cli@v3.3.0
        if: steps.changedfiles.outputs.any_changed == 'true'
        with:
          files: ${{ steps.changedfiles.outputs.all_changed_files }}
          config_file: .github/workflows/config/.markdownlintrc


  spellcheck: # ----------------------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: getfiles
        run: |
           echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} \
                 | grep '.yml' | xargs)"
      - uses: rojopolis/spellcheck-github-actions@0.33.0


#  linkcheck: # -------------------------------------------------------------
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v3


